### ISSUE TITLE
이 CoC의 라이선스가 궁금합니다

### ISSUE THREAD

**Issue by dolsup** [spoqa/code-of-conduct#2]
이 CoC를 기반으로 CoC를 만들려고 합니다.
내용 변경이 가능한지, 출처를 표기해야 하는지 여부를 알고 싶습니다.
어떤 라이선스인지 명시해주시면 감사하겠습니다.

**Comment by kanghyojun** [comment]
@dolsup 안녕하세요. 스포카 크리에이터팀 강효준입니다.

현재 스포카 기술 블로그는 별도로 CC 라이선스를 표기하고 있지는 않으나,
저작자 표시-비영리(CC BY-NC) 라이선스를 적용하고 있다고 생각해주시면 될 것 같습니다.

문의 만들어주셔서 감사합니다!

**Comment by dolsup** [comment]
친절한 답변 감사합니다. 😊
